on:
  create:
    tags:
      - '*'

name: publish

jobs:
  lint:
    name: publish

    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.MAGAZORD_DOCKERHUB_USER}}
          DOCKER_PASS: ${{secrets.MAGAZORD_DOCKERHUB_PASS}}
        run: |
          docker login --username $DOCKER_USER --password $DOCKER_PASS

      - name: Docker Build
        run: |
          docker build  --target app -t magazord/twigger80:latest .

      - name: Docker Publish
        run: |
          docker push magazord/twigger80:latest
